config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/blog', to: 'posts#index'
  devise_for :users
  root 'posts#index'
  get 'about', to: 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner
  has_many :comments, dependent: :destroy
  has_rich_text :body
  validates :title, length: {minimum: 5}
  validates :body, length: {minimum: 25}
  self.per_page = 10
  
  def optimized_image (image, x,y)
    return image.variant(resize_to_fill: [x, y]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy

  def username
    return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin?
  helper_method :is_admin!

  private
  def is_admin?
    if current_user
      return current_user.admin
    else
      return false
    end
  end

  def is_admin!
    if current_user && current_user.admin
    else
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="row" id="comment-<%= comment.id %>">
<div class="container">
<div class="jumbotron">
[<%=comment.created_at.strftime("%I:%M %p") %>]
 <%= comment.user.username %>
 <hr>

 <%= comment.body %>
 <% if current_user && (current_user == comment.user || current_user.admin) %>
 <%= link_to "Delete", post_comment_path(@post, comment), class:'btn btn-danger float-right', method: :delete, remote: true %>
 <% end %>
</div></div></div>

app/views/comments/create.js.erb
$("#comment_pane").prepend("<%= j render @comment %>");
$("#comment_body").val('');

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").html('');

app/views/homes/about.html.erb
<div class="container jumbotron">
  <div class="row">
    <h1>About Me</h1>
    <hr class="my-4" />
  </div>
  <div class="row">
    <p style="text-align:justify">
      Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Cursus euismod quis viverra nibh cras. Blandit volutpat maecenas volutpat blandit aliquam etiam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Adipiscing elit pellentesque habitant morbi. Tellus at urna condimentum mattis pellentesque id. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Laoreet id donec ultrices tincidunt arcu non sodales neque. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Ullamcorper morbi tincidunt ornare massa eget egestas. Cras tincidunt lobortis feugiat vivamus. Neque laoreet suspendisse interdum consectetur libero.
      <br>
      <br>
      Tincidunt arcu non sodales neque sodales. Ornare arcu dui vivamus arcu felis bibendum. Nunc congue nisi vitae suscipit tellus mauris a diam. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Tellus id interdum velit laoreet. Cursus metus aliquam eleifend mi in nulla. Blandit libero volutpat sed cras ornare arcu. Cras adipiscing enim eu turpis egestas pretium aenean. Pharetra massa massa ultricies mi. Enim facilisis gravida neque convallis a cras semper auctor neque. Pulvinar elementum integer enim neque volutpat. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum.
    </p>
    <hr class="my-4" />
  </div>
  <div class="btn-group" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-secondary" onclick="window.location.href = 'https://github.com/Terugu-Kiran';">GitHub</button>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="<%= root_path %>">My Blog</a>
   <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
      >
   <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
            <%= link_to "Home", root_path, class:'nav-link' %>
         </li>
         <li class="nav-item">
            <%= link_to "About", about_path, class:'nav-link' %>
         </li>
      </ul>
      <ul class="navbar-nav ml-auto">
         <% if current_user %>
         <li class="nav-item dropdown">
            <a
               class="nav-link dropdown-toggle"
               href="#"
               id="navbarDropdown"
               role="button"
               data-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false"
               ><%= current_user.username %>
            </a>
            <div
               class="dropdown-menu dropdown-menu-right"
               aria-labelledby="navbarDropdown"
               >
               <% if current_user.admin %> <%= link_to "New Post", new_post_path,
                  class:'dropdown-item' %> <% end %> <%= link_to "Account Settings",
                  edit_user_registration_path, class:'dropdown-item' %>
               <div class="dropdown-divider"></div>
               <%= link_to "Logout", destroy_user_session_path, method: :delete,
                  class:'dropdown-item' %>
            </div>
         </li>
         <% else %>
         <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:'nav-link' %>
         </li>
         <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
         </li>
         <% end %>
      </ul>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string optional' %>
    <%= f.label :thumbnail, class:'form-control' %> 
    <%= f.file_field :thumbnail, class:'form-control' %> 
    <%= f.label :banner, class:'form-control' %>
    <%= f.file_field :banner, class:'form-control' %> 
  </div>
  <div style="margin:1em">
    <%= f.rich_text_area :body %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Posts</h1>
<div class="container">
  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate @posts, :container => false %>
    </div>
  </div>
  <% @posts.each do |post| %>
  <div class="row">
    <div class="card mb-3">
      <img
        class="card-img-top"
        src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>"
        alt="Card image cap"
      />
      <div class="card-body">
        <h5 class="card-title"><%= link_to post.title, post %></h5>
        <p class="card-text"><%= post.body.truncate_words(25) %></p>
        <p class="card-text">
          <small class="text-muted"
            ><%= post.updated_at.strftime("%A, %B %e, %Y") %> by <%=
            post.user.username %> | <%= pluralize(post.views, "View") %></small
          >
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>
<br>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div style="width:100%;height: 300px; overflow-y:hidden">
  <%= image_tag(@post.banner, style:'width:100%;') %>
</div>
<div class="container" style="margin-top:2em">
  <div class="row">
    <div class="jumbotron">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%=
        @post.user.username %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="container">
    <%= form_with model: [@post, @comment] do |f| %> 
      <%= f.text_area :body, class:'form-control', placeholder:'Say something...' %> 
      <%= f.submit "Comment", class:'btn btn-primary float-right' %> 
    <% end %> 
  </div>
</div>

<div id="comment_pane">
<% @comments.each do |comment| %> 
<%= render 'comments/comment', comment: comment %>
<% end %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>